---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Pitao.
--- DateTime: 2024/3/19 16:15
---
local a = 456
a = 123
print(a)
a = a
print(a)
a = g
print(a)
g = 123
print(g)
g = a
print(g)
g = g2
print(g)